version: '3.8'

services:
  ai-tool-analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.local
    volumes:
      - ./debug_output:/app/debug_output
    restart: "no"
    command: python ai_productivity_tools.py